# Generated by Django 4.2.8 on 2024-01-15 08:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_swimposts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimposts',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
