# Generated by Django 4.2.8 on 2024-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_swimposts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimposts',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='swimposts',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
