# Generated by Django 4.2.8 on 2024-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_swimposts_description_alter_swimposts_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimposts',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
