# Generated by Django 4.2.8 on 2024-01-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_swimposts_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimposts',
            old_name='author',
            new_name='creator',
        ),
    ]
