# Generated by Django 4.2.8 on 2024-01-23 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_rename_author_swimposts_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinSwim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('swim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swims_joined', to='home.swimposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_swim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
