# Generated by Django 4.2.8 on 2024-01-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_review_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_location',
            field=models.CharField(default='Where did you swim?', max_length=300),
        ),
    ]
