# Generated by Django 4.2.8 on 2024-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_review_review_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimposts',
            name='title',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
