# Generated by Django 4.2.8 on 2024-01-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_swimposts_title_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimposts',
            name='title',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
