# Generated by Django 4.2.8 on 2024-01-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_swimposts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimposts',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
